// File generated from <ims_init.xsd> at 2018-06-21T11:11:07
static const char* ims_init_xsd =
"<?xml version=\"1.0\" encoding=\"ISO-8859-1\"?>\n"
"\n"
"<!-- \n"
"    * Copyright (c) 2018 Airbus Operations S.A.S                                  *\n"
"    *                                                                             *\n"
"    * This program and the accompanying materials are made available under the    *\n"
"    * terms of the Eclipse Public License v. 2.0 which is available at            *\n"
"    * http://www.eclipse.org/legal/epl-2.0, or the Eclipse Distribution License   *\n"
"    * v. 1.0 which is available at                                                *\n"
"    * http://www.eclipse.org/org/documents/edl-v10.php.                           *\n"
"    *                                                                             *\n"
"    * SPDX-License-Identifier: EPL-2.0 OR BSD-3-Clause                            *\n"
"-->\n"
"\n"
"<xs:schema xmlns:xs=\"http://www.w3.org/2001/XMLSchema\" \n"
"           elementFormDefault=\"unqualified\" \n"
"           attributeFormDefault=\"unqualified\" \n"
"           version=\"1.0\">\n"
"\n"
"  <!--\n"
"      *\n"
"      * Init node\n"
"      *\n"
"  -->\n"
"  <xs:element name=\"Init\">\n"
"    <xs:complexType>\n"
"      <xs:choice minOccurs=\"0\" maxOccurs=\"unbounded\">\n"
"        <xs:element name=\"AfdxSamplingMessage\" type=\"afdx-type\" />\n"
"        <xs:element name=\"A429SamplingLabel\"   type=\"a429-type\" />\n"
"        <xs:element name=\"CanSamplingMessage\"  type=\"can-type\" />\n"
"        <xs:element name=\"DiscreteSignal\"      type=\"discrete-type\" />\n"
"        <xs:element name=\"AnalogueSignal\"      type=\"analogue-type\" />\n"
"      </xs:choice>\n"
"      <xs:anyAttribute namespace=\"##other\" processContents=\"skip\" />\n"
"    </xs:complexType>\n"
"  </xs:element>\n"
"\n"
"  <!--\n"
"      *\n"
"      * AFDX node\n"
"      *\n"
"  -->\n"
"  <xs:complexType name=\"afdx-type\">\n"
"    <xs:attribute name=\"LocalName\" type=\"non-empty-type\" use=\"required\" />\n"
"    <xs:attribute name=\"Value\" type=\"afdx-value-type\" use=\"required\" />\n"
"    <xs:anyAttribute namespace=\"##other\" processContents=\"skip\" />\n"
"  </xs:complexType>\n"
"\n"
"\n"
"\n"
"  <!--\n"
"      *\n"
"      * A429 node\n"
"      *\n"
"  -->\n"
"  <xs:complexType name=\"a429-type\">\n"
"    <xs:attribute name=\"LocalName\" type=\"non-empty-type\" use=\"required\" />\n"
"    <xs:attribute name=\"Value\" type=\"a429-value-type\" use=\"required\" />\n"
"    <xs:anyAttribute namespace=\"##other\" processContents=\"skip\" />\n"
"  </xs:complexType>\n"
"\n"
"\n"
"  <!--\n"
"      *\n"
"      * CAN node\n"
"      *\n"
"  -->\n"
"  <xs:complexType name=\"can-type\">\n"
"    <xs:attribute name=\"LocalName\" type=\"non-empty-type\" use=\"required\" />\n"
"    <xs:attribute name=\"Value\" type=\"can-value-type\" use=\"required\" />\n"
"    <xs:anyAttribute namespace=\"##other\" processContents=\"skip\" />\n"
"  </xs:complexType>\n"
"\n"
"  <!--\n"
"      *\n"
"      * DISCRETE node\n"
"      *\n"
"  -->\n"
"  <xs:complexType name=\"discrete-type\">\n"
"    <xs:attribute name=\"LocalName\" type=\"non-empty-type\" use=\"required\" />\n"
"    <xs:attribute name=\"Value\" type=\"discrete-value-type\" use=\"required\" />\n"
"    <xs:anyAttribute namespace=\"##other\" processContents=\"skip\" />\n"
"  </xs:complexType>\n"
"\n"
"\n"
"\n"
"  <!--\n"
"      *\n"
"      * ANALOGUE node\n"
"      *\n"
"  -->\n"
"  <xs:complexType name=\"analogue-type\">\n"
"    <xs:attribute name=\"LocalName\" type=\"non-empty-type\" use=\"required\" />\n"
"    <xs:attribute name=\"Value\" type=\"xs:float\" use=\"required\" />\n"
"    <xs:anyAttribute namespace=\"##other\" processContents=\"skip\" />\n"
"  </xs:complexType>\n"
"  \n"
"\n"
"  <!--\n"
"      *\n"
"      * Standard simple types\n"
"      *\n"
"  -->\n"
"  <xs:simpleType name='non-empty-type'>\n"
"    <xs:restriction base='xs:token'>\n"
"      <xs:minLength value='1'/>\n"
"    </xs:restriction>\n"
"  </xs:simpleType>\n"
"\n"
"  <xs:simpleType name='discrete-value-type'>\n"
"    <xs:restriction base='xs:string'>\n"
"      <xs:enumeration value=\"0\"/>\n"
"      <xs:enumeration value=\"1\"/>\n"
"      <xs:enumeration value=\"true\"/>\n"
"      <xs:enumeration value=\"false\"/>\n"
"      <xs:enumeration value=\"TRUE\"/>\n"
"      <xs:enumeration value=\"FALSE\"/>\n"
"    </xs:restriction>\n"
"  </xs:simpleType>\n"
"\n"
"  <xs:simpleType name='afdx-value-type'>\n"
"    <xs:restriction base=\"xs:string\">\n"
"      <xs:pattern value='[0-9A-Fa-f]+'/>\n"
"    </xs:restriction>\n"
"  </xs:simpleType>\n"
"\n"
"  <xs:simpleType name='a429-value-type'>\n"
"    <xs:restriction base=\"xs:string\">\n"
"      <xs:pattern value='[0-9A-Fa-f]{2,8}'/>\n"
"    </xs:restriction>\n"
"  </xs:simpleType>\n"
"\n"
"  <xs:simpleType name='can-value-type'>\n"
"    <xs:restriction base=\"xs:string\">\n"
"      <xs:pattern value='[0-9A-Fa-f]{2,16}'/>\n"
"    </xs:restriction>\n"
"  </xs:simpleType>\n"
"  \n"
"\n"
"\n"
"</xs:schema>\n"
"\n";
