// File generated from <ims_config.xsd> at 2018-06-21T11:11:07
static const char* ims_config_xsd =
"<?xml version=\"1.0\" encoding=\"ISO-8859-1\"?>\n"
"\n"
"<!-- \n"
"    * Copyright (c) 2018 Airbus Operations S.A.S                                  *\n"
"    *                                                                             *\n"
"    * This program and the accompanying materials are made available under the    *\n"
"    * terms of the Eclipse Public License v. 2.0 which is available at            *\n"
"    * http://www.eclipse.org/legal/epl-2.0, or the Eclipse Distribution License   *\n"
"    * v. 1.0 which is available at                                                *\n"
"    * http://www.eclipse.org/org/documents/edl-v10.php.                           *\n"
"    *                                                                             *\n"
"    * SPDX-License-Identifier: EPL-2.0 OR BSD-3-Clause                            *\n"
"-->\n"
"\n"
"<xs:schema xmlns:xs=\"http://www.w3.org/2001/XMLSchema\" \n"
"           elementFormDefault=\"unqualified\" \n"
"           attributeFormDefault=\"unqualified\" \n"
"           version=\"1.0\">\n"
"\n"
"  <!--\n"
"      * \n"
"      * VirtualComponent node\n"
"      *\n"
"  -->\n"
"  <xs:element name=\"VirtualComponent\">\n"
"    <xs:complexType>\n"
"      <xs:sequence>\n"
"        <xs:element name=\"DataExchange\" type=\"data-exchange-type\" minOccurs=\"0\" maxOccurs=\"1\"/>\n"
"        <xs:element name=\"Equipment\"    type=\"equipment-type\"     minOccurs=\"0\" maxOccurs=\"unbounded\"/>\n"
"      </xs:sequence>\n"
"      <xs:attribute name=\"Name\"                type=\"non-empty-type\"        use=\"required\" />\n"
"      <xs:attribute name=\"ProdId\"              type=\"xs:nonNegativeInteger\" use=\"optional\" />\n"
"      <xs:attribute name=\"StartupRunningState\" type=\"running-state-type\"    use=\"optional\" />\n"
"      <xs:attribute name=\"PowerState\"          type=\"power-state-type\"      use=\"optional\" />\n"
"      <xs:anyAttribute namespace=\"##other\" processContents=\"skip\"/>\n"
"    </xs:complexType>\n"
"  </xs:element>\n"
"\n"
"\n"
"  <!--\n"
"      *\n"
"      * Equipment node\n"
"      *\n"
"  -->\n"
"  <xs:complexType name=\"equipment-type\">\n"
"    <xs:sequence>\n"
"      <xs:element name=\"DataExchange\" type=\"data-exchange-type\" minOccurs=\"0\" maxOccurs=\"1\"/>\n"
"      <xs:element name=\"Application\"  type=\"application-type\"   minOccurs=\"0\" maxOccurs=\"unbounded\"/>\n"
"    </xs:sequence>\n"
"    <xs:attribute name=\"Name\" type=\"non-empty-type\" use=\"required\" />\n"
"    <xs:anyAttribute namespace=\"##other\" processContents=\"skip\"/>\n"
"  </xs:complexType>\n"
"\n"
"\n"
"  <!--\n"
"      *\n"
"      * Application node\n"
"      *\n"
"  -->\n"
"  <xs:complexType name=\"application-type\">\n"
"    <xs:sequence>\n"
"      <xs:element name=\"DataExchange\" type=\"data-exchange-type\" minOccurs=\"0\" maxOccurs=\"1\"/>\n"
"    </xs:sequence>\n"
"    <xs:attribute name=\"Name\" type=\"non-empty-type\" use=\"required\" />\n"
"    <xs:anyAttribute namespace=\"##other\" processContents=\"skip\"/>\n"
"  </xs:complexType>\n"
"\n"
"\n"
"\n"
"  <!--\n"
"      *\n"
"      * DataExchange node\n"
"      *\n"
"  -->\n"
"  <xs:complexType name=\"data-exchange-type\">\n"
"    <xs:all>\n"
"      <xs:element name=\"AFDX\"     type=\"afdx-type\"     minOccurs=\"0\" maxOccurs=\"1\"/>\n"
"      <xs:element name=\"A429\"     type=\"a429-type\"     minOccurs=\"0\" maxOccurs=\"1\"/>\n"
"      <xs:element name=\"CAN\"      type=\"can-type\"      minOccurs=\"0\" maxOccurs=\"1\"/>\n"
"      <xs:element name=\"DISCRETE\" type=\"discrete-type\" minOccurs=\"0\" maxOccurs=\"1\"/>\n"
"      <xs:element name=\"ANALOGUE\" type=\"analogue-type\" minOccurs=\"0\" maxOccurs=\"1\"/>\n"
"      <xs:element name=\"NAD\"      type=\"nad-type\"      minOccurs=\"0\" maxOccurs=\"1\"/>\n"
"    </xs:all>\n"
"    <xs:anyAttribute namespace=\"##other\" processContents=\"skip\"/>\n"
"  </xs:complexType>\n"
"\n"
"\n"
"\n"
"  <!--\n"
"      *\n"
"      * AFDX node\n"
"      *\n"
"  -->\n"
"  <xs:complexType name=\"afdx-type\">\n"
"    <xs:all>\n"
"      <xs:element name=\"ConsumedData\" type=\"afdx-direction-type\" minOccurs=\"0\" maxOccurs=\"1\"/>\n"
"      <xs:element name=\"ProducedData\" type=\"afdx-direction-type\" minOccurs=\"0\" maxOccurs=\"1\"/>\n"
"    </xs:all>\n"
"    <xs:anyAttribute namespace=\"##other\" processContents=\"skip\"/>\n"
"  </xs:complexType>\n"
"\n"
"  <xs:complexType name=\"afdx-direction-type\">\n"
"    <xs:choice maxOccurs=\"unbounded\">\n"
"      <xs:element name=\"SamplingMessage\" type=\"afdx-sampling-type\" minOccurs=\"0\" maxOccurs=\"1\"/>\n"
"      <xs:element name=\"QueuingMessage\"  type=\"afdx-queuing-type\"  minOccurs=\"0\" maxOccurs=\"1\"/>      \n"
"    </xs:choice>\n"
"    <xs:anyAttribute namespace=\"##other\" processContents=\"skip\"/>\n"
"  </xs:complexType>\n"
"\n"
"  <xs:complexType name=\"afdx-sampling-type\">\n"
"    <xs:attribute name=\"Name\"               type=\"non-empty-type\"        use=\"required\" />\n"
"    <xs:attribute name=\"LocalName\"          type=\"non-empty-type\"        use=\"required\" />\n"
"    <xs:attribute name=\"MessageSizeBytes\"   type=\"xs:positiveInteger\"    use=\"required\" />\n"
"    <xs:attribute name=\"ValidityDurationUs\" type=\"xs:nonNegativeInteger\" use=\"required\" />\n"
"    <xs:attribute name=\"PeriodUs\"           type=\"xs:nonNegativeInteger\" use=\"optional\" />\n"
"    <xs:anyAttribute namespace=\"##other\" processContents=\"skip\"/>\n"
"  </xs:complexType>\n"
"\n"
"  <xs:complexType name=\"afdx-queuing-type\">\n"
"    <xs:attribute name=\"Name\"         type=\"non-empty-type\"     use=\"required\" />\n"
"    <xs:attribute name=\"LocalName\"    type=\"non-empty-type\"     use=\"required\" />\n"
"    <xs:attribute name=\"MaxSizeBytes\" type=\"xs:positiveInteger\" use=\"required\" />\n"
"    <xs:attribute name=\"QueueDepth\"   type=\"xs:positiveInteger\" use=\"required\" />\n"
"    <xs:anyAttribute namespace=\"##other\" processContents=\"skip\"/>\n"
"  </xs:complexType>\n"
"\n"
"\n"
"\n"
"  <!--\n"
"      *\n"
"      * A429 node\n"
"      *\n"
"  -->\n"
"  <xs:complexType name=\"a429-type\">\n"
"    <xs:all>\n"
"      <xs:element name=\"ConsumedData\" type=\"a429-direction-type\" minOccurs=\"0\" maxOccurs=\"1\"/>\n"
"      <xs:element name=\"ProducedData\" type=\"a429-direction-type\" minOccurs=\"0\" maxOccurs=\"1\"/>\n"
"    </xs:all>\n"
"    <xs:anyAttribute namespace=\"##other\" processContents=\"skip\"/>\n"
"  </xs:complexType>\n"
"\n"
"  <xs:complexType name=\"a429-direction-type\">\n"
"    <xs:sequence>\n"
"      <xs:element name=\"Bus\" type=\"a429-bus-type\" minOccurs=\"0\" maxOccurs=\"unbounded\" />\n"
"    </xs:sequence>\n"
"    <xs:anyAttribute namespace=\"##other\" processContents=\"skip\"/>\n"
"  </xs:complexType>\n"
"\n"
"  <xs:complexType name=\"a429-bus-type\">\n"
"    <xs:choice maxOccurs=\"unbounded\">\n"
"      <xs:element name=\"SamplingLabel\" type=\"a429-sampling-type\" minOccurs=\"0\" maxOccurs=\"1\"/>\n"
"      <xs:element name=\"QueuingLabel\"  type=\"a429-queuing-type\"  minOccurs=\"0\" maxOccurs=\"1\"/>      \n"
"    </xs:choice>\n"
"    <xs:attribute name=\"Name\" type=\"non-empty-type\" use=\"required\" />\n"
"    <xs:anyAttribute namespace=\"##other\" processContents=\"skip\"/>\n"
"  </xs:complexType>\n"
"\n"
"  <xs:complexType name=\"a429-sampling-type\">\n"
"    <xs:attribute name=\"Number\"             type=\"label-number-type\"       use=\"required\" />\n"
"    <xs:attribute name=\"Sdi\"                type=\"sdi-type\"                use=\"required\" />\n"
"    <xs:attribute name=\"LocalName\"          type=\"non-empty-type\"          use=\"required\" />\n"
"    <xs:attribute name=\"ValidityDurationUs\" type=\"xs:nonNegativeInteger\"   use=\"required\" />\n"
"    <xs:attribute name=\"PeriodUs\"           type=\"xs:nonNegativeInteger\"   use=\"optional\" />\n"
"    <xs:anyAttribute namespace=\"##other\" processContents=\"skip\"/>\n"
"  </xs:complexType>\n"
"\n"
"  <xs:complexType name=\"a429-queuing-type\">\n"
"    <xs:attribute name=\"Number\"             type=\"label-number-type\"       use=\"required\" />\n"
"    <xs:attribute name=\"Sdi\"                type=\"sdi-type\"                use=\"required\" />\n"
"    <xs:attribute name=\"LocalName\"          type=\"non-empty-type\"          use=\"required\" />\n"
"    <xs:attribute name=\"QueueDepth\"         type=\"xs:nonNegativeInteger\"   use=\"required\" />\n"
"    <xs:anyAttribute namespace=\"##other\" processContents=\"skip\"/>\n"
"  </xs:complexType>\n"
"\n"
"\n"
"\n"
"  <!--\n"
"      *\n"
"      * CAN node\n"
"      *\n"
"  -->\n"
"  <xs:complexType name=\"can-type\">\n"
"    <xs:all>\n"
"      <xs:element name=\"ConsumedData\" type=\"can-direction-type\" minOccurs=\"0\" maxOccurs=\"1\"/>\n"
"      <xs:element name=\"ProducedData\" type=\"can-direction-type\" minOccurs=\"0\" maxOccurs=\"1\"/>\n"
"    </xs:all>\n"
"    <xs:anyAttribute namespace=\"##other\" processContents=\"skip\"/>\n"
"  </xs:complexType>\n"
"\n"
"  <xs:complexType name=\"can-direction-type\">\n"
"    <xs:sequence>\n"
"      <xs:element name=\"Bus\" type=\"can-bus-type\" minOccurs=\"0\" maxOccurs=\"unbounded\" />\n"
"    </xs:sequence>\n"
"    <xs:anyAttribute namespace=\"##other\" processContents=\"skip\"/>\n"
"  </xs:complexType>\n"
"\n"
"  <xs:complexType name=\"can-bus-type\">\n"
"    <xs:choice maxOccurs=\"unbounded\">\n"
"      <xs:element name=\"SamplingMessage\" type=\"can-sampling-type\" minOccurs=\"0\" maxOccurs=\"1\">\n"
"        <xs:key name=\"att\">\n"
"            <xs:selector xpath=\".\"/>\n"
"            <xs:field xpath=\"@DefaultId|@Id\"/>\n"
"        </xs:key>\n"
"      </xs:element>\n"
"      <xs:element name=\"QueuingMessage\"  type=\"can-queuing-type\"  minOccurs=\"0\" maxOccurs=\"1\"/>      \n"
"    </xs:choice>\n"
"    <xs:attribute name=\"Name\" type=\"non-empty-type\" use=\"required\" />\n"
"    <xs:anyAttribute namespace=\"##other\" processContents=\"skip\"/>\n"
"  </xs:complexType>\n"
"\n"
"  <xs:complexType name=\"can-sampling-type\">\n"
"    <xs:simpleContent>\n"
"        <xs:extension base=\"xs:string\">\n"
"            <xs:attribute name=\"DefaultId\"          type=\"can-id-type\"                            />\n"
"            <xs:attribute name=\"Id\"                 type=\"can-id-type\"                            />\n"
"            <xs:attribute name=\"LocalName\"          type=\"non-empty-type\"          use=\"required\" />\n"
"            <xs:attribute name=\"MessageSizeBytes\"   type=\"xs:nonNegativeInteger\"   use=\"required\" />\n"
"            <xs:attribute name=\"ValidityDurationUs\" type=\"xs:nonNegativeInteger\"   use=\"required\" />\n"
"            <xs:attribute name=\"PeriodUs\"           type=\"xs:nonNegativeInteger\"   use=\"optional\" />\n"
"            <xs:anyAttribute namespace=\"##other\" processContents=\"skip\"/>\n"
"        </xs:extension>\n"
"    </xs:simpleContent>\n"
"  </xs:complexType>\n"
"\n"
"  <xs:complexType name=\"can-queuing-type\">\n"
"    <xs:anyAttribute processContents=\"skip\"/> <!-- Not supported yet -->\n"
"  </xs:complexType>\n"
"\n"
"  <!--\n"
"      *\n"
"      * DISCRETE node\n"
"      *\n"
"  -->\n"
"  <xs:complexType name=\"discrete-type\">\n"
"    <xs:all>\n"
"      <xs:element name=\"ConsumedData\" type=\"discrete-direction-type\" minOccurs=\"0\" maxOccurs=\"1\"/>\n"
"      <xs:element name=\"ProducedData\" type=\"discrete-direction-type\" minOccurs=\"0\" maxOccurs=\"1\"/>\n"
"    </xs:all>\n"
"    <xs:anyAttribute namespace=\"##other\" processContents=\"skip\"/>\n"
"  </xs:complexType>\n"
"\n"
"  <xs:complexType name=\"discrete-direction-type\">\n"
"    <xs:sequence>\n"
"      <xs:element name=\"Signal\" type=\"discrete-signal-type\" minOccurs=\"0\" maxOccurs=\"unbounded\" />\n"
"    </xs:sequence>\n"
"    <xs:anyAttribute namespace=\"##other\" processContents=\"skip\"/>\n"
"  </xs:complexType>\n"
"\n"
"  <xs:complexType name=\"discrete-signal-type\">\n"
"    <xs:attribute name=\"Name\"          type=\"non-empty-type\"        use=\"required\" />\n"
"    <xs:attribute name=\"LocalName\"     type=\"non-empty-type\"        use=\"required\" />\n"
"    <xs:attribute name=\"TrueState\"     type=\"xs:nonNegativeInteger\" use=\"optional\" />\n"
"    <xs:attribute name=\"FalseState\"    type=\"xs:nonNegativeInteger\" use=\"optional\" />\n"
"    <xs:attribute name=\"HWPP\"          type=\"hwpp-value-type\"       use=\"optional\" />\n"
"    <xs:attribute name=\"PeriodUs\"      type=\"xs:nonNegativeInteger\" use=\"optional\" />\n"
"    <xs:attribute name=\"ValidityDurationUs\" type=\"xs:nonNegativeInteger\" use=\"optional\" />\n"
"    <xs:anyAttribute namespace=\"##other\" processContents=\"skip\"/>\n"
"  </xs:complexType>\n"
"\n"
"\n"
"\n"
"  <!--\n"
"      *\n"
"      * ANALOGUE node\n"
"      *\n"
"  -->\n"
"  <xs:complexType name=\"analogue-type\">\n"
"    <xs:all>\n"
"      <xs:element name=\"ConsumedData\" type=\"analogue-direction-type\" minOccurs=\"0\" maxOccurs=\"1\"/>\n"
"      <xs:element name=\"ProducedData\" type=\"analogue-direction-type\" minOccurs=\"0\" maxOccurs=\"1\"/>\n"
"    </xs:all>\n"
"    <xs:anyAttribute namespace=\"##other\" processContents=\"skip\"/>\n"
"  </xs:complexType>\n"
"\n"
"  <xs:complexType name=\"analogue-direction-type\">\n"
"    <xs:sequence>\n"
"      <xs:element name=\"Signal\" type=\"analogue-signal-type\" minOccurs=\"0\" maxOccurs=\"unbounded\" />\n"
"    </xs:sequence>\n"
"    <xs:anyAttribute namespace=\"##other\" processContents=\"skip\"/>\n"
"  </xs:complexType>\n"
"\n"
"  <xs:complexType name=\"analogue-signal-type\">\n"
"    <xs:attribute name=\"Name\"          type=\"non-empty-type\" use=\"required\" />\n"
"    <xs:attribute name=\"LocalName\"     type=\"non-empty-type\" use=\"required\" />\n"
"    <xs:attribute name=\"ScaleFactor\"   type=\"xs:float\"       use=\"required\" />\n"
"    <xs:attribute name=\"Offset\"        type=\"xs:float\"       use=\"required\" />\n"
"    <xs:attribute name=\"PeriodUs\"      type=\"xs:nonNegativeInteger\" use=\"optional\" />\n"
"    <xs:attribute name=\"ValidityDurationUs\" type=\"xs:nonNegativeInteger\" use=\"optional\" />\n"
"    <xs:anyAttribute namespace=\"##other\" processContents=\"skip\"/>\n"
"  </xs:complexType>\n"
"\n"
"\n"
"  <!--\n"
"      *\n"
"      * NAD node\n"
"      *\n"
"  -->\n"
"  <xs:complexType name=\"nad-type\">\n"
"    <xs:all>\n"
"      <xs:element name=\"ConsumedData\" type=\"nad-direction-type\" minOccurs=\"0\" maxOccurs=\"1\"/>\n"
"      <xs:element name=\"ProducedData\" type=\"nad-direction-type\" minOccurs=\"0\" maxOccurs=\"1\"/>\n"
"    </xs:all>\n"
"    <xs:anyAttribute namespace=\"##other\" processContents=\"skip\"/>\n"
"  </xs:complexType>\n"
"\n"
"  <xs:complexType name=\"nad-direction-type\">\n"
"    <xs:sequence>\n"
"      <xs:element name=\"Message\" type=\"nad-message-type\" minOccurs=\"0\" maxOccurs=\"unbounded\" />\n"
"    </xs:sequence>\n"
"    <xs:anyAttribute namespace=\"##other\" processContents=\"skip\"/>\n"
"  </xs:complexType>\n"
"\n"
"  <xs:complexType name=\"nad-message-type\">\n"
"    <xs:attribute name=\"Name\"             type=\"non-empty-type\"     use=\"required\" />\n"
"    <xs:attribute name=\"LocalName\"        type=\"non-empty-type\"     use=\"required\" />\n"
"    <xs:attribute name=\"MessageSizeBytes\" type=\"xs:positiveInteger\" use=\"required\" />\n"
"    <xs:attribute name=\"PeriodUs\"         type=\"xs:nonNegativeInteger\" use=\"optional\" />\n"
"    <xs:attribute name=\"MessageType\"       type=\"message-type-enum\" use=\"optional\" />\n"
"    <xs:attribute name=\"MessageDimension1\" type=\"xs:nonNegativeInteger\" use=\"optional\" />\n"
"    <xs:attribute name=\"MessageDimension2\" type=\"xs:nonNegativeInteger\" use=\"optional\" />\n"
"    <xs:anyAttribute namespace=\"##other\" processContents=\"skip\"/>\n"
"  </xs:complexType>\n"
"\n"
"\n"
"\n"
"  <!--\n"
"      *\n"
"      * Standard simple types\n"
"      *\n"
"  -->\n"
"  <xs:simpleType name='non-empty-type'>\n"
"    <xs:restriction base='xs:token'>\n"
"      <xs:minLength value='1'/>\n"
"    </xs:restriction>\n"
"  </xs:simpleType>\n"
"\n"
"  <xs:simpleType name='label-number-type'>\n"
"    <xs:restriction base='xs:string'>\n"
"      <xs:pattern value='[0-3]?[0-7]?[0-7]'/>\n"
"    </xs:restriction>\n"
"  </xs:simpleType>\n"
"\n"
"  <xs:simpleType name='sdi-type'>\n"
"    <xs:restriction base='xs:string'>\n"
"      <xs:enumeration value=\"00\"/>\n"
"      <xs:enumeration value=\"01\"/>\n"
"      <xs:enumeration value=\"10\"/>\n"
"      <xs:enumeration value=\"11\"/>\n"
"      <xs:enumeration value=\"DD\"/>\n"
"      <xs:enumeration value=\"XX\"/>\n"
"      <xs:enumeration value=\"NU\"/>\n"
"    </xs:restriction>\n"
"  </xs:simpleType>\n"
"\n"
"  <xs:simpleType name='message-type-enum'>\n"
"    <xs:restriction base='xs:string'>\n"
"      <xs:enumeration value=\"BOOLEAN\"/>\n"
"      <xs:enumeration value=\"C08\"/>\n"
"      <xs:enumeration value=\"F32\"/>\n"
"      <xs:enumeration value=\"F64\"/>\n"
"      <xs:enumeration value=\"I16\"/>\n"
"      <xs:enumeration value=\"I32\"/>\n"
"      <xs:enumeration value=\"I64\"/>\n"
"    </xs:restriction>\n"
"  </xs:simpleType>\n"
"\n"
"  <xs:simpleType name='discrete-value-type'>\n"
"    <xs:restriction base='xs:string'>\n"
"      <xs:enumeration value=\"0\"/>\n"
"      <xs:enumeration value=\"1\"/>\n"
"      <xs:enumeration value=\"true\"/>\n"
"      <xs:enumeration value=\"false\"/>\n"
"      <xs:enumeration value=\"TRUE\"/>\n"
"      <xs:enumeration value=\"FALSE\"/>\n"
"    </xs:restriction>\n"
"  </xs:simpleType>\n"
"\n"
"\n"
"  <xs:simpleType name='hwpp-value-type'>\n"
"    <xs:restriction base='xs:string'>\n"
"      <xs:enumeration value=\"yes\"/>\n"
"      <xs:enumeration value=\"no\"/>\n"
"      <xs:enumeration value=\"YES\"/>\n"
"      <xs:enumeration value=\"NO\"/>\n"
"    </xs:restriction>\n"
"  </xs:simpleType>\n"
"\n"
"\n"
"  <xs:simpleType name='can-id-type'>\n"
"    <xs:restriction base=\"xs:string\">\n"
"      <xs:pattern value='[0-9A-Fa-f]{1,8}'/>\n"
"    </xs:restriction>\n"
"  </xs:simpleType>\n"
"  \n"
"\n"
"  <xs:simpleType name='running-state-type'>\n"
"    <xs:restriction base='xs:string'>\n"
"      <xs:enumeration value=\"run\"/>\n"
"      <xs:enumeration value=\"step\"/>\n"
"      <xs:enumeration value=\"hold\"/>\n"
"      <xs:enumeration value=\"reset\"/>\n"
"    </xs:restriction>\n"
"  </xs:simpleType>\n"
"\n"
"  <xs:simpleType name='power-state-type'>\n"
"    <xs:restriction base='xs:string'>\n"
"      <xs:enumeration value=\"on\"/>\n"
"      <xs:enumeration value=\"off\"/>\n"
"    </xs:restriction>\n"
"  </xs:simpleType>\n"
"\n"
"</xs:schema>\n"
"\n";
